[build]
  command = "cd ProyectoServidorT2 && npm install && npm run build"
  publish = "ProyectoServidorT2/dist/ProyectoServidorT2/browser"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200